/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as AppLayoutRouteImport } from './pages/_app/layout'
import { Route as AppIndexRouteImport } from './pages/_app/index'
import { Route as AppProductsIndexRouteImport } from './pages/_app/products/index'
import { Route as AppAuthSingUpRouteImport } from './pages/_app/_auth/sing-up'
import { Route as AppAuthSignInRouteImport } from './pages/_app/_auth/sign-in'

const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppProductsIndexRoute = AppProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppAuthSingUpRoute = AppAuthSingUpRouteImport.update({
  id: '/_auth/sing-up',
  path: '/sing-up',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppAuthSignInRoute = AppAuthSignInRouteImport.update({
  id: '/_auth/sign-in',
  path: '/sign-in',
  getParentRoute: () => AppLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/sign-in': typeof AppAuthSignInRoute
  '/sing-up': typeof AppAuthSingUpRoute
  '/products': typeof AppProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/sign-in': typeof AppAuthSignInRoute
  '/sing-up': typeof AppAuthSingUpRoute
  '/products': typeof AppProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppLayoutRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/_auth/sign-in': typeof AppAuthSignInRoute
  '/_app/_auth/sing-up': typeof AppAuthSingUpRoute
  '/_app/products/': typeof AppProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sign-in' | '/sing-up' | '/products'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sign-in' | '/sing-up' | '/products'
  id:
    | '__root__'
    | '/_app'
    | '/_app/'
    | '/_app/_auth/sign-in'
    | '/_app/_auth/sing-up'
    | '/_app/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/products/': {
      id: '/_app/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AppProductsIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_auth/sing-up': {
      id: '/_app/_auth/sing-up'
      path: '/sing-up'
      fullPath: '/sing-up'
      preLoaderRoute: typeof AppAuthSingUpRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_auth/sign-in': {
      id: '/_app/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AppAuthSignInRouteImport
      parentRoute: typeof AppLayoutRoute
    }
  }
}

interface AppLayoutRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppAuthSignInRoute: typeof AppAuthSignInRoute
  AppAuthSingUpRoute: typeof AppAuthSingUpRoute
  AppProductsIndexRoute: typeof AppProductsIndexRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppAuthSignInRoute: AppAuthSignInRoute,
  AppAuthSingUpRoute: AppAuthSingUpRoute,
  AppProductsIndexRoute: AppProductsIndexRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppLayoutRoute: AppLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
